{ config, osConfig, ... }:
let
  c = config.lib.stylix.colors; # hex values without '#'
  monitors = osConfig.dotfiles.monitors;
  xkb = osConfig.services.xserver.xkb;
in
{
  # hyprland.lua stays a plain dotfile. This only generates a Lua file with
  # the values that the NixOS config also knows: monitor names, keyboard
  # layout and theme colors. hyprland.lua loads it with
  # `pcall(require, "nix.generated")` and falls back to its own defaults on
  # machines without Nix. Same idea as kitty.nix.
  xdg.configFile."hypr/nix/generated.lua".text = ''
    -- Generated by home-manager (nix/modules/home/hyprland.nix). Do not edit.
    return {
        -- dotfiles.monitors in configuration.nix
        monitors = {
            main = "${monitors.main}",
            left = "${monitors.left}",
        },
        -- services.xserver.xkb in configuration.nix
        keyboard = {
            layout  = "${xkb.layout}",
            variant = "${xkb.variant}",
            options = "${xkb.options}",
        },
        -- stylix theme in style.nix
        colors = {
            border_active   = "rgba(${c.base0D}ff)", -- base0D (blue)
            border_inactive = "rgba(${c.base03}ff)", -- base03 (grey)
            shadow          = 0x40${c.base05},       -- base05 (text color) at 25% opacity (0xAARRGGBB)
        },
    }
  '';
}
