{ config, ... }:
let
  c = config.lib.stylix.colors.withHashtag;
in
{
  # Only the colors of kitty are managed here, as a generated file that
  # .config/kitty/kitty.conf includes when it exists (globinclude, which does
  # nothing if the file is missing). kitty.conf itself stays a plain dotfile,
  # because kitty is also used on machines without Nix. On those, the default
  # theme (themes/catppuccin_latte.conf) stays active.
  #
  # The globinclude is currently commented out in kitty.conf until the shell
  # prompt is styled, too. Until then, this file is generated but not used.
  #
  # programs.kitty and the stylix kitty target are deliberately not used, as
  # they would generate the whole kitty.conf and collide with the dotfile.
  # Mapping from base16 to kitty colors as in the base16-kitty template.
  xdg.configFile."kitty/nix/stylix.conf".text = ''
    # Generated by home-manager from the stylix theme (nix/modules/home/kitty.nix).
    # Do not edit, change the theme in nix/modules/style.nix.
    foreground            ${c.base05}
    background            ${c.base00}
    selection_foreground  ${c.base00}
    selection_background  ${c.base05}
    cursor                ${c.base05}
    cursor_text_color     ${c.base00}
    url_color             ${c.base04}

    active_border_color   ${c.base03}
    inactive_border_color ${c.base01}
    bell_border_color     ${c.base08}

    tab_bar_background    ${c.base01}
    active_tab_background ${c.base00}
    active_tab_foreground ${c.base05}
    inactive_tab_background ${c.base01}
    inactive_tab_foreground ${c.base04}

    color0  ${c.base00}
    color1  ${c.base08}
    color2  ${c.base0B}
    color3  ${c.base0A}
    color4  ${c.base0D}
    color5  ${c.base0E}
    color6  ${c.base0C}
    color7  ${c.base05}
    color8  ${c.base03}
    color9  ${c.base08}
    color10 ${c.base0B}
    color11 ${c.base0A}
    color12 ${c.base0D}
    color13 ${c.base0E}
    color14 ${c.base0C}
    color15 ${c.base07}
    color16 ${c.base09}
    color17 ${c.base0F}
    color18 ${c.base01}
    color19 ${c.base02}
    color20 ${c.base04}
    color21 ${c.base06}
  '';
}
